version: '3.8'

services:
    sio_test:
        container_name: sio_test
        user: app
        build:
            context: .
            args:
                USER_ID: ${USER_ID}
        ports:
            - "8337:8337"
        volumes:
            - .:/app:rw
        environment:
            - APP_ENV=dev
        depends_on:
            - database
        networks:
            - app_network

    database:
        container_name: postgres
        image: postgres:16-alpine
        environment:
            POSTGRES_DB: ${POSTGRES_DB:-app}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
            POSTGRES_USER: ${POSTGRES_USER:-app}
        ports:
            - "5432:5432"
        networks:
            - app_network

    adminer:
        container_name: adminer
        image: adminer
        restart: always
        ports:
            - "8080:8080"
        networks:
            - app_network

networks:
    app_network:
